### ISSUE TITLE
Refactoring routes

### ISSUE THREAD

**Issue by SriramPatibanda** [dscnitrourkela/project-avocado#112]
In the current app, while using routes, the app uses strings to mention the specific page and this can cause typos and ultimately errors while coding.

It is better to refactor the code such that we can just declare the string in that specific screen and tap into that constant from anywhere easily thereby reducing typos and errors.

**Comment by DesignrKnight** [comment]
If I understand correctly, we will have a utility file which will manage the routes. Isn't it?

Sounds like something that will improve the codebase

**Comment by SriramPatibanda** [comment]
Not exactly. I basically added 

> If I understand correctly, we will have a utility file which will manage the routes. Isn't it?
> 
> Sounds like something that will improve the codebase

Not exactly, I created a static const String (id) at every page which stores the name of the route. So you can easily tap into the route by using something like HomePage.id.

**Comment by SriramPatibanda** [comment]
@DesignrKnight Please assign this to me. I would like to work on it.

**Comment by DesignrKnight** [comment]
I am not really sure of this implementation. Imagine the home screen which is the gateway to all other screens. In this, it'll have to refer each of the class to get its route. Won't having one route utility file be better?

CC: @Thesmader

**Comment by SriramPatibanda** [comment]
> I am not really sure of this implementation. Imagine the home screen which is the gateway to all other screens. In this, it'll have to refer each of the class to get its route. Won't having one route utility file be better?
> 
> CC: @Thesmader

Ok, so creating a class named routes, adding all the static const strings under that and just calling the routes class wherever required would be better maybe?
