### ISSUE TITLE
Make it compatible to new Android Embedding

### ISSUE THREAD

**Issue by nayakastha** [dscnitrourkela/project-avocado#114]
![001](https://user-images.githubusercontent.com/58568514/95250749-24970580-0838-11eb-984d-b45dba2b50ed.PNG)

This warning is received in the latest stable version of Flutter (1.22.0) on completion of -flutter pub get

**Comment by DesignrKnight** [comment]
Warning
──────────────────────────────────────────────────────────────────────────────
Your Flutter application is created using an older version of the Android
embedding. It's being deprecated in favor of Android embedding v2. Follow the
steps at

https://flutter.dev/go/android-project-migration

to migrate your project.

**Comment by DesignrKnight** [comment]
In continuation of a conversation with @SriramPatibanda at #117 
Assigning you the same

**Comment by SriramPatibanda** [comment]
> @DesignrKnight I'm getting this error while trying to run the app. I'm not sure but (FaqActivity.java uses unchecked or unsafe operations) FaqActivity.java might need some modifications. But the main error arises in Application.java.
> Please help me if you know the solution for this.
Never mind. Changing the Application.java file solved the issue.

**Comment by Thesmader** [comment]
@Chinmay-KB mind taking a look at the native kotlin code?
