### ISSUE TITLE
The project needs to be migrated as it uses an older version of Android embedding.

### ISSUE THREAD

**Issue by SriramPatibanda** [dscnitrourkela/project-avocado#117]
You get build errors and the following warning while you try to run the app after upgrading to the latest flutter version:

Your Flutter application is created using an older version of the Android
embedding. It's being deprecated in favor of Android embedding v2. Follow the
steps at
https://flutter.dev/go/android-project-migration
to migrate your project.

**Comment by SriramPatibanda** [comment]
@DesignrKnight  Please assign me to this issue. I tend to follow the instructions given at https://flutter.dev/go/android-project-migration and migrate the project so that the conflict is solved.

**Comment by DesignrKnight** [comment]
Duplicate of #114 
Assigning you #114
