### ISSUE TITLE
Add a Contact via WhatsApp feature

### ISSUE THREAD

**Issue by pratik0197** [dscnitrourkela/project-avocado#120]
The message button in mentor's details has functionality of sending text messages. Text messages are usually ignored by most. How about adding a contact via WhatsApp feature? That way, the mentees can directly contact their mentors on whatsapp even if their number is not saved.

**Comment by DesignrKnight** [comment]
We could. Only problem being many numbers aren't WhatsApp numbers.

**Comment by pratik0197** [comment]
Yes. I didn't consider that
