### ISSUE TITLE
Update Time Table automatically with date

### ISSUE THREAD

**Issue by pratik0197** [dscnitrourkela/project-avocado#121]
The Time Table of First year seems to be fixed to the Autumn Semester only. 

For example, the timings of sections seem to be still in Autumn semester without the sequence being changed. 

Can check the present date for whether it is in Spring or Autumn semester and render the timetable accordingly? :)

**Comment by DesignrKnight** [comment]
Assigned

**Comment by DesignrKnight** [comment]
Do update us when done. Will look forward to how you do it

**Comment by pratik0197** [comment]
Planning to do it in the following way:

1. Determine the current month using DateTime.now().month
2. If the month is greater than 8, Time table to remain same. Else, reassign the practical and theory section to the corresponding sections.

The explanation for corresponding sections:
P1-P5 have same schedule in PT as P6-P10 have in TP and vice versa. Similarly, A-D in PT have same as E-H in TP and vice versa.

So, if the currentMonth is greater than 8, reassign the section in the background.

For reassigning, in TimeTableResource class, I have made a mapping for the same purpose.

Is this approach good to go with?

**Comment by DesignrKnight** [comment]
Reassign section as in the section of the user?

**Comment by DesignrKnight** [comment]
Let's say I am in A section
I will still be in A section in Spring, but my timetable will be same as E section's from Autumn sem

**Comment by DesignrKnight** [comment]
Also, what about subjects like Maths - I and Maths - II?

**Comment by pratik0197** [comment]
> Let's say I am in A section
> I will still be in A section in Spring, but my timetable will be same as E section's from Autumn sem

Yes. That's what I'm planning to do.

**Comment by pratik0197** [comment]
> Also, what about subjects like Maths - I and Maths - II?

Working on that currently :)

**Comment by pratik0197** [comment]
> Also, what about subjects like Maths - I and Maths - II?

Actually , I have added it to the TODO in my commit after modifying that theory and practical section for spring semester . Thinking to find a way out to solve that issue in as less modifications as possible. 


[That commit link.](https://github.com/pratik0197/project-avocado/commit/cdcf6b0b41e4b87de3e172b266aec9660cfe0332).

**Comment by pratik0197** [comment]
> > Let's say I am in A section
> > I will still be in A section in Spring, but my timetable will be same as E section's from Autumn sem
> 
> Yes. That's what I'm planning to do.

What I hav done is, as the theory section or practical sections are not displayed anywhere in the App, I have added a map to find the corresponding section in the Autumn Semester. That is if I am in Section A, and it is spring semester, the section in the app will be changed to E and it's time table will be displayed. Is that a correct way? Because I have not seen anywhere the section or practical section displayed to the user in the app and found this to be the way to with minimal changes. If you reckon, I might try something to do it using some other way
