### ISSUE TITLE
Dynamically Show the information about the members of ICS.

### ISSUE THREAD

**Issue by pratik0197** [dscnitrourkela/project-avocado#136]
- Presently, the information about the faculty members and other members of the ICS have been hardcoded. The information may change after one sometime(maybe the faculty members change or the students coordinating may change.) and it may be feasible if we show them dynamically.

- I would like to propose fetching the information from firebase and rendering the same dynamically.

**Comment by DesignrKnight** [comment]
@riteshsp2000

We will have API for these, isn't it?
Or Firebase?

**Comment by DesignrKnight** [comment]
Why did you close this? 😂
This is a feature that needs to be done at some point
