### ISSUE TITLE
[url_launcher] When targeting API 30, canLaunch always returns false

### ISSUE THREAD

**Issue by abhibhaw** [dscnitrourkela/project-avocado#137]
Launch URL plugin isn't working!

**To Reproduce**
Upgrade the Android SDK Version to 30.
**Expected behavior**
A URL in the default browser should launch.

**Tested on:**
 - Device: One Plus 8
 - OS: Android 11.0

**Additional context**
- Should work on clicking the privacy policy of the side navbar.
- And the cards of FAQ, Notification, Dev Info etc.
## Console Log
`E/flutter (14738): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: Could not launch https://project-avocado-8b3e1.firebaseapp.com
E/flutter (14738): #0      _HomePageState._launchURL (package:scp/HomePage.dart:335:7)
E/flutter (14738): <asynchronous suspension>
E/flutter (14738): #1      _HomePageState.build.<anonymous closure>.<anonymous closure> (package:scp/HomePage.dart:128:27)
E/flutter (14738): #2      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:993:19)
E/flutter (14738): #3      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:1111:38)
E/flutter (14738): #4      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:183:24)
E/flutter (14738): #5      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:598:11)
E/flutter (14738): #6      BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:287:5)
E/flutter (14738): #7      BaseTapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:259:7)
E/flutter (14738): #8      GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:157:27)
E/flutter (14738): #9      GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:362:20)
E/flutter (14738): #10     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:338:22)
E/flutter (14738): #11     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:267:11)
E/flutter (14738): #12     GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:295:7)
E/flutter (14738): #13     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:240:7)
E/flutter (14738): #14     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:213:7)
E/flutter (14738): #15     _rootRunUnary (dart:async/zone.dart:1206:13)
E/flutter (14738): #16     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
E/flutter (14738): #17     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
E/flutter (14738): #18     _invoke1 (dart:ui/hooks.dart:265:10)
E/flutter (14738): #19     _dispatchPointerDataPacket (dart:ui/hooks.dart:174:5)
E/flutter (14738): `

## Flutter Doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 1.22.4, on Microsoft Windows [Version 10.0.18363.1198], locale en-IN)
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[!] Android Studio (version 4.1.0)
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
[√] VS Code (version 1.51.1)
[√] Connected device (1 available)

! Doctor found issues in 1 category.

**Comment by abhibhaw** [comment]
# Reference of this:

[URL Launcher Issue](https://github.com/flutter/flutter/issues/63727)
[Android 11 Package Visibility Guide](https://developer.android.com/training/basics/intents/package-visibility)

**Comment by DesignrKnight** [comment]
@abhibhaw 
Can you fix this and migrate entire app to v30 SDK?

**Comment by abhibhaw** [comment]
@DesignrKnight Easiest way to fix the issue is to wait for the plugin's author to push an update for SDK 30.  Still, I will try [Package Visibility](https://developer.android.com/training/basics/intents/package-visibility)
