### ISSUE TITLE
[WoC] Services - Create a SharedPreferences service

### ISSUE THREAD

**Issue by Thesmader** [dscnitrourkela/project-avocado#177]
Minimum requirements for the service:
1. A function to return an instance of SharedPreferences.
2. A function(private to the service) to save different types of content to disk using SharedPreferences.

[Reference](https://www.filledstacks.com/snippet/shared-preferences-service-in-flutter-for-code-maintainability/)

**Comment by Chinmay-KB** [comment]
To add to what @Thesmader has mentioned, make sure every fetch operation you make is checked with containsKey

**Comment by Chinmay-KB** [comment]
Sometimes we need to clear a bunch of keys, like
* Deleting theory and practical sections while resetting section
* Reset all data while logging out
Have functions in this service that can achieve the said functionality in one click, currently all the keys that need to be deleted are called individually and deleted
