### ISSUE TITLE
[WoC] ViewModels - Appointments View Model

### ISSUE THREAD

**Issue by Chinmay-KB** [dscnitrourkela/project-avocado#179]
## Scope
The following can be added to Appointments
* getData()
* _setupRemoteConfig() (This can be named more appropriately
* Initialising ScpDatabase (SCP is the old name of ICS)

Feel free to add to this list if you find anything worth migrating to AppointmentsViewModel

**Comment by DesignrKnight** [comment]
Hey @Chinmay-KB why do we need Remote Config in Appointments?
We will have reset on cloud I suppose. If there is any dynamic data, let us store in RLDB itself along with other appointments data

**Comment by Chinmay-KB** [comment]
The function remoteconfig does things more than just remote config 
Hence I wrote it can be named more appropriately

**Comment by Priya-81199** [comment]
It is getDate() right and not getData()? And we have to implement stacked in the appointment.dart and new file on the same file hierarchy appointments_viewmodel.dart?

**Comment by Chinmay-KB** [comment]
We can move the whole appointments thing to a folder of its own
