### ISSUE TITLE
Add Link for the sophomore year timetable in the timetable section.

### ISSUE THREAD

**Issue by nayakastha** [dscnitrourkela/project-avocado#221]

**Comment by DesignrKnight** [comment]
Add the link in the side navigation drawer or similar places. The primary audience of the app remains the freshers and it better to have a seamless access for freshers by using the primary features for them and not provide multiple paths for the users who are in freshmen year

**Comment by nayakastha** [comment]
Yes. Added it in the important document section to prevent any kind of confusion.
