### ISSUE TITLE
Change all the print statements in the project to debugPrint

### ISSUE THREAD

**Issue by SriramPatibanda** [dscnitrourkela/project-avocado#228]

**Comment by HustleAura** [comment]
I want to work.

**Comment by ayyysh04** [comment]
can I work on this?

**Comment by abhibhaw** [comment]
sure @ayyysh04 , Not only change, but also do remove the unnecessary print statements which aren't relevant for the project now.

**Comment by abhibhaw** [comment]
Fixed by #252
