### ISSUE TITLE
Build failed due to use of deprecated Android v1 embedding.

### ISSUE THREAD

**Issue by abhibhaw** [dscnitrourkela/project-avocado#255]
Build Logs: [Codemagic Logs](https://api.codemagic.io/builds/63333d21dd6888a78e92ab55/step/63333d21e7c9f2ac0c8fd71e)

Fix Ref: [Flutter migration guide](https://flutter.dev/go/android-project-migration)

**Comment by asutoshranjan** [comment]
Assign me this issue
