### ISSUE TITLE
Blank screen before exiting the app

### ISSUE THREAD

**Issue by Chinmay-KB** [dscnitrourkela/project-avocado#30]
When we hit the back button from the homepage, we expect to exit the app. Instead it shows a black screen first, then we need to hit the back button again to exit the app

**Comment by AmaldevAD** [comment]
i would suggest you to keep main.dart file codes as much less as possible

**Comment by sudhansu3299** [comment]
I think keeping Scaffold in the top of widget tree will help. Shall i go for it?

**Comment by DesignrKnight** [comment]
#53

**Comment by SriramPatibanda** [comment]
I think instead of exiting the app on a single-click, it's better to add a prompt saying "click again to exit the app".
Would like to work on this issue.

**Comment by DesignrKnight** [comment]
Assigning you the same, look at the linked PR as @Chinmay-KB had done something, you may use that.

Additionally, I am not really sure about a prompt asking, if someone wants to exit the app, makes sense here? It is helpful in places like video conferencing.
