### ISSUE TITLE
Display Splash Screen

### ISSUE THREAD

**Issue by Thesmader** [dscnitrourkela/project-avocado#32]
Display splash screen until the user is logged in

**Comment by Thesmader** [comment]
Could get a nice Flare animation for Splash Screen.

**Comment by hkp27299** [comment]
I can work on it make PR after 1st October

**Comment by DesignrKnight** [comment]
Thank you for your interest. 
Should I assign this to you?

**Comment by hkp27299** [comment]
yes sure can you tell me what is this app for so i can design related splash screen?

**Comment by DesignrKnight** [comment]
Check out the app on play store
[https://play.google.com/store/apps/details?id=in.ac.nitrkl.scp.scp&hl=en](https://play.google.com/store/apps/details?id=in.ac.nitrkl.scp.scp&hl=en)

**Comment by hkp27299** [comment]
oky asign this to me thnx for support.

**Comment by DesignrKnight** [comment]
The App uses Firebase authentication and would not sign for releases from new devices.due to SHA mismatch. 
We would share a workaround for the same soon.

**Comment by hkp27299** [comment]
oky

**Comment by DesignrKnight** [comment]
There is a Slack channel for this. If you are interested, you can send your email address here

**Comment by hkp27299** [comment]
I have some issue while compile it some firebase import error because it will missing 
google-services.jason
![Screenshot (3)](https://user-images.githubusercontent.com/44067918/65833317-a92d7a80-e2ec-11e9-8b6d-51edd068f691.png)

**Comment by DesignrKnight** [comment]
Kindly send the email address associated with your Firebase account. We'll give you access

**Comment by hkp27299** [comment]
hkp27299@gmail.com

**Comment by DesignrKnight** [comment]
Added you into Firebase project. You can download the JSON from there and add to the project before building.

**Comment by hkp27299** [comment]
oky thnx

**Comment by hkp27299** [comment]
still Auth error =====>
![Screenshot (4)](https://user-images.githubusercontent.com/44067918/65835586-d8041a80-e305-11e9-8ac0-ce1e13afd6e3.png)

**Comment by DesignrKnight** [comment]
Use phone number as 1234567890
OTP 123456

**Comment by hkp27299** [comment]
Bro i am almost done with this i will make pr after  day..

**Comment by abhibhaw** [comment]
@Chinmay-KB Closing this?

**Comment by Chinmay-KB** [comment]
PR #168 adds this
