### ISSUE TITLE
Automatic reset of slots booked weekly

### ISSUE THREAD

**Issue by DesignrKnight** [dscnitrourkela/project-avocado#36]
**Proposed solution**
1. A Firebase Cloud Functions based function to reset them weekly via an Admin Panel type configuration
2. An admin app on mobile with similar features

**Present Case**
A maintainer needs to manually do it by editing the database

**Comment by Gauravmauryaios** [comment]
I would like to work on this issue as well

**Comment by DesignrKnight** [comment]
Hey, we have decided to solve this issue internally within the team. Due to some concerns, we are not publishing the Node.js cloud functions on a public domain

Thank you for your interest
