### ISSUE TITLE
Revamp Design of Mentor's Detail Page

### ISSUE THREAD

**Issue by DesignrKnight** [dscnitrourkela/project-avocado#69]
**Describe the solution you'd like**
The mentor's page has very basic design as of now. It should be improved to make it consistent with the overall theme of app in other sections

**Comment by nayakastha** [comment]
I want to work on this.

**Comment by Thesmader** [comment]
Hey, @nayakastha glad to know that! Do you have a specific design on your mind? If so, please send an image or talk about it here. Thanks!

**Comment by nayakastha** [comment]
I was thinking about modifying the text field a bit. More like placing the whole form in the centre of the page.

**Comment by DesignrKnight** [comment]
Go ahead.
Would recommend having a sketch if possible. Even a paper sketch of what design you are planning. Help in coding as well

**Comment by nayakastha** [comment]
![Screenshot_20200812_225456](https://user-images.githubusercontent.com/58568514/90047344-65b6e180-dcef-11ea-829b-9dabdf448d64.jpg)

**Comment by nayakastha** [comment]
This has the basic changes I have made. If there are any more suggestions, I will incorporate them as well.

**Comment by DesignrKnight** [comment]
What about the next page? After I click the tick?

**Comment by nayakastha** [comment]
I haven't thought about it. Are there any particular changes I should take care of?

**Comment by DesignrKnight** [comment]
@Thesmader 
Can you send some sample neat design for inspiration?

**Comment by Thesmader** [comment]
Let me find something. But it's not gonna be like we can use it directly. We can derive some inspiration but in the end we need the design consistent with the app😀

**Comment by Thesmader** [comment]
https://dribbble.com/shots/5676730-Team-Section-Qonto
Something like the card shown on the right screen on this design could work. We don't need the profile picture right now. The call to actions for phone, email can be there along with the relevant info. Also, do you guys think if a call to action for WhatsApp can be of help if the implementation is possible?

**Comment by nayakastha** [comment]
I will try to implement something of that sort.

**Comment by DesignrKnight** [comment]
Any progress @nayakastha ?
