### ISSUE TITLE
Have the app show the user the network connectivity status

### ISSUE THREAD

**Issue by DesignrKnight** [dscnitrourkela/project-avocado#70]
**Describe the solution you'd like**
Inspiration can be taken from YouTube which shows at the bottom a message when the user goes offline and/or comes back online.

This should be done modular so that it can cover all sections of the app

**Comment by rajnis09** [comment]
I would like to work on this if you assign me

**Comment by DesignrKnight** [comment]
Yeah, definitely
Assigning you

Thanks for the initiative

**Comment by rajnis09** [comment]
Thanks to you
can you share the .json file?

**Comment by DesignrKnight** [comment]
Share your Firebase mail address, will add you

**Comment by rajnis09** [comment]
rajnish.kumar2998@gmail.com

**Comment by DesignrKnight** [comment]
Added you on the project at Firebase

**Comment by rajnis09** [comment]
Thanks
