### ISSUE TITLE
Not able to build debug apk

### ISSUE THREAD

**Issue by DesignrKnight** [dscnitrourkela/project-avocado#71]
**Describe the bug**
The present code on building a debug apk causes an error

**To Reproduce**
Try to build a debug apk

**Comment by abhibhaw** [comment]
@DesignrKnight @Thesmader 

**flutter build apk --debug** is working in the following manner....

flutter clean
flutter pub get
flutter build apk --debug

Got this Output [apk-debug.apk](https://drive.google.com/file/d/1nlqLc7mbOrDRjm8y5Nk24xMDnHrATj3a/view?usp=sharing)

Have a look.

**Comment by DesignrKnight** [comment]
@nayakastha @SriramPatibanda @abhibhaw If this issue is not present in latest project versions, feel free to close

**Comment by nayakastha** [comment]
It's working fine for me. Let others just confirm. Will close this.

**Comment by abhibhaw** [comment]
Working fine for me too 👍

**Comment by abhibhaw** [comment]
All working fine! Reopen if it fails for someone.
