### ISSUE TITLE
Make links intuitive

### ISSUE THREAD

**Issue by DesignrKnight** [dscnitrourkela/project-avocado#73]
The links of website and intents that open phone for the call are not intuitive. A demarcation with a colour/text-style would enhance user-experience.

Refer the Developer Info, About ICS Page, Important Docs.

**Comment by nayakastha** [comment]
I would like to work on this issue

**Comment by DesignrKnight** [comment]
Hello
Can you mail from your mail associated with Firebase? We will add you as a collaborator, without that you won't be able to build the project.

**Comment by DesignrKnight** [comment]
The link of above-mentioned pages can have a look and feel like the notification section of the app. You may refer.
What we are referring as link are phone number email and website that on clicking open new activity outside the app

**Comment by nayakastha** [comment]
Hey!
This is my mail associated with firebase as well.
