### ISSUE TITLE
Fix Landscape rotation

### ISSUE THREAD

**Issue by DesignrKnight** [dscnitrourkela/project-avocado#77]
![image](https://user-images.githubusercontent.com/27865704/88013393-eabc3a00-cb39-11ea-8416-ae925438d9c6.png)

**Comment by abhibhaw** [comment]
Hey,

I want to work on this issue... and for the same, I need google services.json file.

**Comment by DesignrKnight** [comment]
@Thesmader 
You'll do the Google services sharing, I suppose.
