### ISSUE TITLE
Trim Roll Number in the middleware.

### ISSUE THREAD

**Issue by pratik0197** [dscnitrourkela/project-avocado#93]
While opening the app for the first time, and while searching for mentors, Roll number has to be entered. If an extra space is present after or before the roll number it's not accepted as a valid one.

**Comment by DesignrKnight** [comment]
This looks like a good issue to work on. Do you want to work on this?

**Comment by pratik0197** [comment]
Yes. I'd like to work on this

**Comment by DesignrKnight** [comment]
Go ahead, all the best. Assigned

**Comment by DesignrKnight** [comment]
Hey, any updates
Any help needed from us?

**Comment by pratik0197** [comment]
Yes. I am on it. Currently I am going through the code. I will update it in 3-4 days :)

**Comment by pratik0197** [comment]
There is just a problem @DesignrKnight , I am not able to run it locally on physical device in Android Studio, is there any firebase configuration I need to take care of ?

**Comment by DesignrKnight** [comment]
Send your Firebase mail ID

**Comment by pratik0197** [comment]
priyadarshanpratik123@gmail.com

**Comment by DesignrKnight** [comment]
Have given you access to Firebase. Download the google-services.json from there and you should be good to go

Test Login Numbers
![Uploading image.png…]()

**Comment by DesignrKnight** [comment]
Have given you access to Firebase. Download the google-services.json from there and you should be good to go

Test Login Numbers
![image](https://user-images.githubusercontent.com/27865704/95288247-774ade80-0885-11eb-9c5d-8d40dd73eb95.png)
